### ISSUE TITLE
Readme incomplete and outdated

### ISSUE THREAD

**Issue by vspinu** [sunng87/link#25]
Some parts of the docs are outdated. For instance the decoder/encoder examples don't work as `encode*` now accepts 3 arguments.  `send` in the example should be `send!`. There is also no such thing as `link.core/channel-option` anymore. 

The readme also doesn't contain a complete working example. I cannot figure out how to make it  work.  For instance the following doesn't work as the `send!` in the last line seem to have no effect:

```clj

  (def custom-codec
    (codec/frame
      (codec/byte)
      (codec/string :encoding :utf8 :prefix (codec/uint16))))
  
  (def echo-handler
    (link/create-handler
      (link/on-message [ch msg]
                       (link/send! ch msg))))

  (def print-handler
    (link/create-handler
      (link/on-message [ch msg]
                       (println "msg:" msg))))

  (def srv (tcp/tcp-server 8081 [(codec/netty-encoder custom-codec)
                                 (codec/netty-decoder custom-codec)
                                 {:handler echo-handler}]
                           :options {:so-reuseaddr true}))

  (def client-factory
    (tcp/tcp-client-factory [(codec/netty-encoder custom-codec)
                             (codec/netty-decoder custom-codec)
                             {:handler print-handler}]))

  (def cl (tcp/tcp-client client-factory "localhost" 8081))
  (link/send! cl [1 "blabla"]) ;; <- nothing happens after this
```

**Comment by vspinu** [comment]
It actually started working, so nevermind about my issue. Leaving this open as a documentation issue.

**Comment by sunng87** [comment]
Sorry for inconvenience. The document is actually unmaintained for some time, while link api keeps evolving in last few months.
Let me find some free time to correct it, and add a few examples for it. Thank you for reporting. Feel free to ask if you have any question about this lib.

**Comment by sunng87** [comment]
Fixed

**Comment by vspinu** [comment]
Thanks!
