### ISSUE TITLE
Shouldn't codec/string throw on missing :prefix and :delimiter?  

### ISSUE THREAD

**Issue by vspinu** [sunng87/link#26]
I have misspelled `:perfix` instead of `:prefix` in `codec/string`, and oh boy, it took me good couple of hours to figure that out :/ This is why I wrongly reported an issue in #25 btw. 

So my question is whether this [cond](https://github.com/sunng87/link/blob/master/src/link/codec.clj#L61-L72) should actually throw when neither :prefix nor :delimiter are supplied?

**Comment by sunng87** [comment]
Good suggestion. I will throw an `IllegalArgumentException` for that case

**Comment by sunng87** [comment]
Fixed in ae41e1c
